# Generated by Django 5.2.7 on 2025-10-26 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('moedas_atribuidas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('evidencia_foto', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('motivo_recusa', models.TextField(blank=True, null=True)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes_validadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.tipodoacao')),
            ],
        ),
    ]
