# Generated by Django 5.2.8 on 2025-11-24 19:10

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doacoes", "0002_badge_usuariobadge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={
                "ordering": ["tipo", "custo_moedas"],
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
            },
        ),
        migrations.AlterModelOptions(
            name="doacao",
            options={
                "ordering": ["-data_submissao"],
                "verbose_name": "Doação",
                "verbose_name_plural": "Doações",
            },
        ),
        migrations.RemoveField(
            model_name="badge",
            name="imagem_url",
        ),
        migrations.AddField(
            model_name="badge",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="badge",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="badge",
            name="criterio_doacoes",
            field=models.IntegerField(
                blank=True, help_text="Número de doações necessárias", null=True
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="criterio_moedas",
            field=models.IntegerField(
                blank=True, help_text="Total de moedas ganhas necessárias", null=True
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="icone",
            field=models.ImageField(blank=True, null=True, upload_to="badges/"),
        ),
        migrations.AddField(
            model_name="badge",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CONQUISTA", "Conquista Automática"),
                    ("COMPRA", "Disponível para Compra"),
                    ("ESPECIAL", "Badge Especial"),
                ],
                default="CONQUISTA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="custo_moedas",
            field=models.IntegerField(
                default=0, help_text="0 para badges de conquista"
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="badge",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="doacao",
            index=models.Index(
                fields=["status", "data_submissao"],
                name="doacoes_doa_status_740d07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doacao",
            index=models.Index(
                fields=["doador", "status"], name="doacoes_doa_doador__a90893_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="badge",
            table="badges",
        ),
    ]
