# Generated by Django 5.2.8 on 2025-11-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doacoes", "0003_alter_badge_options_alter_doacao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doacao",
            name="descricao",
            field=models.TextField(blank=True, default=""),
        ),
    ]
