# Generated by Django 5.2.8 on 2025-11-30 21:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doacoes", "0004_doacao_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="icone",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="icone"
            ),
        ),
        migrations.AlterField(
            model_name="doacao",
            name="descricao",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="doacao",
            name="evidencia_foto",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="evidencia"
            ),
        ),
    ]
